### ISSUE TITLE
Theme VSCODE

### ISSUE THREAD

**Issue by calusbr** [MattDMo/Neon-color-scheme#40]
Could you make it available for VSCODE?

**Comment by MattDMo** [comment]
I'm going to close this as `wontfix`, unfortunately. The internals of VSCode and the theming system are different enough from Sublime that I'd basically have to recreate Neon from scratch, something that I just don't have the time or motivation to do. I'm not a huge fan of VSCode to begin with, although I know a lot of people like it, and it's just not a huge priority of mine to dive into it to the level that I have for Sublime in order to understand it well enough to make as in-depth a color scheme for it as I have with Sublime.

However, as always, anyone is more than welcome to fork Neon and attempt to port it themselves. Maybe I'll revisit this some day in the future, but for now my focus is on maintaining and improving it for Sublime.
