### ISSUE TITLE
Italic operators look confusing

### ISSUE THREAD

**Issue by rfricz** [MattDMo/Neon-color-scheme#42]
First and foremost, I’ve been using Neon in Sublime Text for years and it’s the best. I only wish it was available in VS Code.

I know this is more a matter of taste, but I’d prefer if operators were not italic, like it was before the new release. They look like they don’t belong when the rest of the expression is not italic. The italic pipe character almost looks like a slash in a lot of fonts (Consolas pic attached) and I find that very confusing. Can this be selectively turned off? I don’t want to disable italic completely because in other contexts (like function arguments) it looks good.
![image](https://user-images.githubusercontent.com/36163339/94563811-81f2eb80-0267-11eb-863a-7c98da8c3837.png)

As a side issue, `bar` is wrongly understood as a property name because of the colon in `baz2`.

**Comment by MattDMo** [comment]
I see what you mean. It's an easy change, I'll push it right now.

**Comment by MattDMo** [comment]
As for VS Code -- I've looked into it, but the internals are different enough from Sublime that it would be a whole lot of work to port Neon over. The program itself is okay, I guess, but I honestly like Sublime a lot more, in part because the API is in Python, not JS, and VS Code just doesn't draw me in that much. Sublime is also under active development, and I have first-hand contact with the devs on Discord, so that's a big bonus. To each his own, though.

**Comment by rfricz** [comment]
Oh wow, that was fast. Thanks! I use Sublime for all coding and only resort to VS Code when I need a debugger...
